### ISSUE TITLE
Internal server error after update to NC 27.0.1

### ISSUE THREAD

**Issue by Sommerwiesel** [nextcloud/files_fulltextsearch#236]
Nextcloud just broke after the update to 27.0.1.
After looking into the logs, I could verify, its due to this app.
"occ app:disable files_fulltextsearch" fixes this error immediately.

Please fix this app for NC 27.0.1

<details><summary>Log</summary>
<p>

`{"reqId":"0UKcGfBSBGNWUnFrM6qa","level":3,"time":"2023-07-26T20:25:29+02:00","remoteAddr":"178.200.73.97","user":"--","app":"index","method":"GET","url":"/login","message":"Too few arguments to function OCA\\GroupFolders\\Folder\\FolderManager::__construct(), 1 passed in /srv/nextcloud/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php on line 105 and exactly 4 expected","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0","version":"27.0.1.2","exception":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OCA\\GroupFolders\\Folder\\FolderManager::__construct(), 1 passed in /srv/nextcloud/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php on line 105 and exactly 4 expected","Code":0,"Trace":[{"file":"/srv/nextcloud/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php","line":105,"function":"__construct","class":"OCA\\GroupFolders\\Folder\\FolderManager","type":"->"},{"function":"__construct","class":"OCA\\Files_FullTextSearch\\Service\\GroupFoldersService","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":494,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":466,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":494,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":466,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":494,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/srv/nextcloud/lib/private/ServerContainer.php","line":155,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Service/ProviderService.php","line":122,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Service/ProviderService.php","line":311,"function":"loadProvider","class":"OCA\\FullTextSearch\\Service\\ProviderService","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Service/ProviderService.php","line":282,"function":"loadProvidersFromList","class":"OCA\\FullTextSearch\\Service\\ProviderService","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Service/ProviderService.php","line":102,"function":"loadProvidersFromApp","class":"OCA\\FullTextSearch\\Service\\ProviderService","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Service/ProviderService.php","line":156,"function":"loadProviders","class":"OCA\\FullTextSearch\\Service\\ProviderService","type":"->"},{"file":"/srv/nextcloud/apps/fulltextsearch/lib/Capabilities.php","line":80,"function":"getConfiguredProviders","class":"OCA\\FullTextSearch\\Service\\ProviderService","type":"->"},{"file":"/srv/nextcloud/lib/private/CapabilitiesManager.php","line":74,"function":"getCapabilities","class":"OCA\\FullTextSearch\\Capabilities","type":"->"},{"file":"/srv/nextcloud/lib/private/Template/JSConfigHelper.php","line":166,"function":"getCapabilities","class":"OC\\CapabilitiesManager","type":"->"},{"file":"/srv/nextcloud/lib/private/TemplateLayout.php","line":240,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->"},{"file":"/srv/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/srv/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":213,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":182,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/nextcloud/lib/base.php","line":1071,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/nextcloud/apps/groupfolders/lib/Folder/FolderManager.php","Line":50,"CustomMessage":"--"}}`

</p>
</details>

**Comment by prolibre** [comment]
Probably.

https://github.com/nextcloud/files_fulltextsearch/issues/233

Everyone is waiting patiently for the patch :-)
